### ISSUE TITLE
Add CSS Styling for Better User Experience

### ISSUE THREAD

**Issue by Pranavnk15** [Pranavnk15/Todo-List#1]
Enhance the visual appeal of the application by adding CSS styling 
to improve the user interface and overall user experience.

**Comment by Shubhamraut01** [comment]
Hey @Pranavnk15 , Please assign this issue to me I want contribute to this project

**Comment by Akshatverma01** [comment]
Can you please assign this issue to me. I am good at CSS and making visually appealing .
Tell me your requirements too.

**Comment by Pranavnk15** [comment]
> Hey @Pranavnk15 , Please assign this issue to me I want contribute to this project

@Shubhamraut01 What's the progress??? Plz update

**Comment by Pranavnk15** [comment]
> Can you please assign this issue to me. I am good at CSS and making visually appealing .
> Tell me your requirements too.
>  
>  
>  
> 

@Akshatverma01 What's the progress??? Plz update

**Comment by AparajitaSingh121416** [comment]
heya @Pranavnk15 please assign this issue to me, i have made many visually appealing apps before. i will be highly grateful.

**Comment by Akshatverma01** [comment]
> > Can you please assign this issue to me. I am good at CSS and making visually appealing .
> > Tell me your requirements too.
> 
> @Akshatverma01 What's the progress??? Plz update

Hope will complete by tomorrow .

**Comment by Pranavnk15** [comment]
> heya @Pranavnk15 please assign this issue to me, i have made many visually appealing apps before. i will be highly grateful.

I
f the @Akshatverma01 doesn't completes it by tomorrow i'll assign you the task.

**Comment by Pranavnk15** [comment]
> heya @Pranavnk15 please assign this issue to me, i have made many visually appealing apps before. i will be highly grateful.

till then you can solving other issues

**Comment by Akshatverma01** [comment]
> > heya @Pranavnk15 please assign this issue to me, i have made many visually appealing apps before. i will be highly grateful.
> 
> I f the @Akshatverma01 doesn't completes it by tomorrow i'll assign you the task. 

I am very new to the open source . I'm trying nodemon app.js command but is not executing.
Please try to  understand

**Comment by Pranavnk15** [comment]
> > > heya @Pranavnk15 please assign this issue to me, i have made many visually appealing apps before. i will be highly grateful.
> > 
> > 
> > I f the @Akshatverma01 doesn't completes it by tomorrow i'll assign you the task.
> 
> I am very new to the open source . I'm trying nodemon app.js command but is not executing. Please try to understand

firstly you need to insall nodemon by the command npm install nodemon,
then in the terminal execute the command nodemon app.js, it will open the project at localhost:3000

**Comment by Akshatverma01** [comment]
> > Can you please assign this issue to me. I am good at CSS and making visually appealing .
> > Tell me your requirements too.
> 
> @Akshatverma01 What's the progress??? Plz update

I have made a pull request . Hope you will like the overall Ui of web-page.
![Screenshot (37)](https://github.com/Pranavnk15/Todo-List/assets/121783296/e525fb85-be8a-4f20-a159-c8a1c2dbc45a)

**Comment by Pranavnk15** [comment]
Great UI

**Comment by Akshatverma01** [comment]
> Great UI

Thanks. Will this be count in hactoberfest?

**Comment by Pranavnk15** [comment]
> > Great UI
> 
> Thanks. Will this be count in hactoberfest?

Ya it will You can check your profile at hacktober...
