### ISSUE TITLE
Add github workflows

### ISSUE THREAD

**Issue by Pranavnk15** [Pranavnk15/Todo-List#16]
Try adding a GitHub workflow for auto commenting, on raising a issue, 
or
performing test on pull request

**Comment by Rachit1313** [comment]
Hi Pranav,
I would like to work towards implementing ESlint script in the code and a workflow to parse this through esLint to check for any errors in PR.

**Comment by Pranavnk15** [comment]
> Hi Pranav,
> I would like to work towards implementing ESlint script in the code and a workflow to parse this through esLint to check for any errors in PR.

Hi rachit any update further??

**Comment by Rachit1313** [comment]
> > Hi Pranav,
> > I would like to work towards implementing ESlint script in the code and a workflow to parse this through esLint to check for any errors in PR.
> 
> Hi rachit any update further??

Hey, Sorry Pranav. I just got a bit busy. I'll push the PR today.

**Comment by Rachit1313** [comment]
@Pranavnk15 , Sorry for the delay. I just created a PR for this. Could you please review and let me know if any changes are required?

**Comment by Rachit1313** [comment]
I think I made some issue in fixing the conflict. Could you revert the merge if possible?

**Comment by Pranavnk15** [comment]
> I think I made some issue in fixing the conflict. Could you revert the merge if possible?

I guess I have  reverted it please check

**Comment by Rachit1313** [comment]
Yes, you created a PR. Could you please merge that one.

**Comment by Pranavnk15** [comment]
yep 1 sec

**Comment by Pranavnk15** [comment]
done

**Comment by Pranavnk15** [comment]
I guess there's some error with it, cause, as you can see the latest PR, its not functioning properly, while installing dependecies and checking

**Comment by Rachit1313** [comment]
yup
What happened is that I forked your repo to work on it and while I was
working on it. There were another commits which changes package-lock.json.
I think it would be better if we take the code back to
https://github.com/Pranavnk15/Todo-List/commit/cc4fca335e4cfc899e88a70c04f94e56d643496e

and then I can add the feature again after syncing my fork.

**Comment by Rachit1313** [comment]
After you are done with this step. Could you reopen this issue and the PR.

**Comment by Pranavnk15** [comment]
so should I revert that commit too?

**Comment by Rachit1313** [comment]
I think you're good.  just open a #24

**Comment by Rachit1313** [comment]
Kindly refer to #27

**Comment by Pranavnk15** [comment]
ya done

**Comment by Pranavnk15** [comment]
Thanks for your contribution
