### ISSUE TITLE
Align Edit and Delete buttons

### ISSUE THREAD

**Issue by dalvishruti14** [Pranavnk15/Todo-List#31]
Edit delete buttons are not aligned properly. 
![ed](https://github.com/Pranavnk15/Todo-List/assets/120911455/03ef2f56-90e4-47b3-8bdd-1df1eb39e570)
Kindly assign this issue to me. @Pranavnk15

**Comment by Pranavnk15** [comment]
You can start working on it

**Comment by Pranavnk15** [comment]
![image](https://github.com/Pranavnk15/Todo-List/assets/96475101/29b55e2f-59ae-474f-a4fd-41abe8e60c22)

Seems to be it's aligned properly, please fix it

**Comment by dalvishruti14** [comment]
okay will check
