### ISSUE TITLE
Add a Header with Title

### ISSUE THREAD

**Issue by Pranavnk15** [Pranavnk15/Todo-List#5]
Modify the header.ejs file to include a header with a title (e.g., "My To-Do List") 
and appropriate styling to make it visually appealing.

**Comment by Shubhamraut01** [comment]
Hey @Pranavnk15 , Please assign this issue to me I want contribute to this project

**Comment by gurjott** [comment]
can you please assign me?

**Comment by SajithMinrutha** [comment]
can you assign me?

**Comment by Akshatverma01** [comment]
Assign this issue to me @Pranavnk15 . I have updated the Ui of the web-page.

**Comment by Pranavnk15** [comment]
firstly sync the updated repo, make changes and then only make a PR

**Comment by Akshatverma01** [comment]
Only I have to change the title or other effects?

**Comment by Akshatverma01** [comment]
> firstly sync the updated repo, make changes and then only make a PR

How to snyc?  or clone again.?

**Comment by Pranavnk15** [comment]
there will be a message on your profile under this repo, 
![image](https://github.com/Pranavnk15/Todo-List/assets/96475101/21a4916c-7490-401f-98f1-178ec8dad2aa)

you will view this type of dialog box when you click on sync, just click on update branch

**Comment by Akshatverma01** [comment]
ok

**Comment by Akshatverma01** [comment]
Requested for PR. You can check now.

**Comment by Akshatverma01** [comment]
@Pranavnk15 PR requested.

**Comment by Akshatverma01** [comment]
Thanks for accepting. I would like to contribute more in your projects. Do you have other projects related to Front-End ? Please tag them hacktoberfest or lets make a project with small steps open -source.

**Comment by Pranavnk15** [comment]
currently dont have any project, but I am in collaboration with a project, with my partner, if you wish you can contribute there, below is the link of the projects repo

https://github.com/mehulcode12/Codeens
