### ISSUE TITLE
Create a Footer

### ISSUE THREAD

**Issue by Pranavnk15** [Pranavnk15/Todo-List#6]
Add a footer to the footer.ejs file with a message (e.g., "Open to Contributions") or add social links. 
Style the footer to make it visually appealing.

**Comment by bishwobista** [comment]
What do you want on the footer? assign me

**Comment by Shubhamraut01** [comment]
Hey @Pranavnk15 , Please assign this issue to me I want contribute to this project

**Comment by Pranavnk15** [comment]
> What do you want on the footer? assign me
> 

@bishwobista What's the progress??? Plz update

**Comment by bishwobista** [comment]
I don't know what happened on my end, I thought I submitted  a PR yesterday, but looks like it never went{ you can check on my profile-repo-branch}. I will try sending again.

**Comment by bishwobista** [comment]
No, It was already merged into main. My PR. Why is this issue still open???

**Comment by Pranavnk15** [comment]
![image](https://github.com/Pranavnk15/Todo-List/assets/96475101/dc81ba5a-ef0f-442a-a7e7-c86a88c2d718)
please make it more appealing, and eye catch, separate the footer from main theme, and the footer should be aligned at the end of the page, trying adding switching themes options like dark theme, white theme

**Comment by siddhi-bajpai** [comment]
Hello @Pranavnk15, I'd like to work on this issue. Could you please assign it to me?

**Comment by Pranavnk15** [comment]
> Hello @Pranavnk15, I'd like to work on this issue. Could you please assign it to me?

you can start working on it

**Comment by PrathameshTheurkar** [comment]
HIi can u assign this issue to me plz . I am a Frontend Developer and I would like to contribute to this issue.

**Comment by Pranavnk15** [comment]
> HIi can u assign this issue to me plz . I am a Frontend Developer and I would like to contribute to this issue.

this is already under work, try solving some other issue
